config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  resources :quotes


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :quotes
  validates :name, presence: true

  
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :company
  validates :name, presence: :true

  after_create_commit -> { broadcast_prepend_to "quotes" }
  after_update_commit -> { broadcast_replace_to "quotes" }
  after_destroy_commit -> { broadcast_destroy_to "quotes" }

  scope :ordered, -> {order(created_at: :desc)}
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  belongs_to :company

  def name
    email.split('@').first.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :authenticate_user!, unless: :devise_controller?

  def current_company
    @current_company ||= current_user.company if user_signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  def index
    @quotes = current_company.quotes.ordered
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = current_company.quotes.build(quote_params)
    
    if @quote.save
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully created." }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @quote.update(quote_params)
      redirect_to quotes_path, notice: 'quote have been updated'
    else
      render :edit
    end
  end

  def destroy
    @quote.destroy
    respond_to do |format|
      format.html {redirect_to quotes_path, notice: 'quote have been destroyed'}
      format.turbo_stream
    end
    
  end

  private

  def set_quote
    @quote = current_company.quotes.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <% if user_signed_in? %>
    <div class="navbar_brand">
      current_company.name
    </div>
    <div class="navbar_name">
      <%= current_user.name %>
    </div>
    <%= button_to 'Logout', method: :delete, class: 'btn btn--dark' %>
  <% else %>
    <%= link_to  'login', new_user_session_path, class: 'btn btn--dark navbar__right'%>  
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Quote Editor" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<main class="container">
  <h1>Quote Editor</h1>
  <p>hotwire quote editor</p>

  <%= if user_signed_in? %>
    <%= link_to 'View Quotes', quotes_path, class: 'btn btn--dark' %>
  <%= else %>
    <%= link_to 'Login', new_user_session_path, class: 'btn btn--dark' %>
  <%= end %>
</main>

app/views/quotes/_form.html.erb
<%= simple_form_for quote, html: {class: "quote form"} do |f| %> 
  <% if quote.errors.any? %>
    <div class="error-message">
      <%= quote.errors.full_messages.to_sentence %> 
    </div>
  <%end%>
 
  <%=  f.input :name %>
  <br>
  <div id="buttons">
    <%= button_to 'cancel',  quotes_path, class: 'btn btn--primary' %>  
    <%= f.submit  class: 'btn btn--secondary' %>
  </div>
  
  
<%end%>
  

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
  <div class="quote">
    
    <%= link_to quote.name, quote_path(quote), data: {turbo_frame: '_top'}%>
    <div class="quote_actions">

      <%= button_to 'delete', quote_path(quote), method: :delete, class: 'btn btn--light' %> 
      <%= link_to 'edit', edit_quote_path(quote), class: 'btn btn--light' %> 
    </div>
  </div>
<%end%>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>

app/views/quotes/destroy.html.erb
<%= turbo_stream.remove "quote_#{@quote.id}" %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove "quote_#{@quote.id}" %>

app/views/quotes/edit.html.erb
<main class="container">
  <%= link_to 'back to quotes', quotes_path %>

  <div class="header">
    <h1>edit quote</h1>

    
  </div>
  <%= turbo_frame_tag @quote do %>
    <%= render 'form', quote: @quote %>
  <%end%>
</main>

app/views/quotes/index.html.erb
<main class="container">
  <%= turbo_stream_from 'quotes' %>
  <div class="header">
    <h1>Quotes</h1>
    <%= link_to "New quote", new_quote_path, class: "btn btn--primary", data: { turbo_frame: dom_id(Quote.new) } %>
  </div>

  <%= turbo_frame_tag Quote.new %>
  <div id="quotes">
    <%= render @quotes %>
  </div>

</main> 

app/views/quotes/new.html.erb
<main class="container">
  <%= link_to 'back to quotes', quotes_path %>
  <div class="header">
    <h1>New Quote</h1>
    <%= turbo_frame_tag @quote do %> 
      <%= render 'form', quote: @quote %> 
    <%end%>
  </div>
  
</main>

app/views/quotes/show.html.erb
<main class="container">
  <%=link_to "back to quotes", quotes_path %>

  <div class="header">
    <h1>
      <%= @quote.name %>
    </h1>
  </div>
</main>